void displayPicture(int width, int height, const unsigned int picture[]);
void displayAvatars(int x, int y, int animal);
void select(int animal);
void drawCharacterAvatar(int x, int y, int animal, int is_goup);
void characterMove(int x, int y, int round);
void drawGate(int round);
void displayMap(int round, int is_lose);
void drawLog(int x, int y, int is_lose);
void drawCar(int x, int y, int is_left, int is_lose);
void carMove(int x, int y, int round, int is_lose);
void logMove(int x, int y, int is_lose);
void displaySkull();
void drawChar(unsigned char c, int x1, int y1, unsigned int attr);
void drawString(char *s, int x1, int y1, unsigned int attr);
int isTree(int x, int y, int round);
int displayInstruction(int round);
void trainMove(int x, int is_lose);
void displayWelcomeScreen(int character);