void displayPicture(int width, int height, const unsigned int picture[]);
void display_avatars(int x, int y, int animal);
void select(int animal);
void drawAvatar(int x, int y, int animal);
void avatarMove(int x, int y, int round);
void draw_gate1();
void display_map1();
void display_map2();
void display_gate1();
void drawLog(int x, int y);
void drawCar(int x, int y, int is_left);
void carMove(int x, int y, int round);
void logMove(int x, int y);
