void displayPicture(int width, int height, unsigned int *picture);
void display_avatars(int x, int y, int animal);
void select(int animal);
void drawAvatar(int x, int y, int animal);
void avatarMove(int x, int y);
void draw_gate1();
void display_map1();
void display_gate1();
void drawCar(int x, int y, int is_left);
void carMove(int x, int y);
